### ISSUE TITLE
Create new page for tracking Events

### ISSUE THREAD

**Issue by michaelyql** [AY2425S1-CS2103T-T10-4/tp#45]
## Description
We want to create a separate page to handle and keep track of upcoming events. 

The events page should have all of the same functionality of the Persons page, i.e. add event, update event, list all events, delete event, filter event. 

Each 

## Issue Type
Epic

## Acceptance Criteria
- [ ] Create a new model to represent an `Event`
- [ ] Create a list that can store all the list of events
- [ ] Implement `event` command to add new events
- [ ] Implement `cancel` command to delete events
- [ ] Implement `update` command to update events
- [ ] Implement `view` command to view detailed event information
- [ ] Add new UI page for 'Events' tab
- [ ] Add list view for event list under events tab
- [ ] Add event detail view when user clicks on event in event list
