### ISSUE TITLE
Implement tracking Persons attending an Event

### ISSUE THREAD

**Issue by Gilbb** [AY2425S1-CS2103T-T10-4/tp#99]
## Description
Implement tracking Persons attending an Event

## Issue Type
Enhancement
Related issues: #92 

## Acceptance Criteria
- [ ] Ensure that `event` can support attendees
- [ ] Ensure that `update` can support attendees
- [ ] `Event` is updated dynamically with a set of attendees
- [ ] Serialize list of attendees and store as JSON in `EventBook.json`

**Comment by michaelyql** [comment]
Closed for duplicate
